"""This script contains the pf_batchrun() and md_batchrun() functions."""

import os


def pf_batchrun():
    os.system(
        # Insert new python commands below this line

        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_003_Session_7_13052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_003_Session_8_11102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_003_Session_9_26052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_005_Session_10_21092022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_005_Session_7_28062021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_005_Session_8_06102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_005_Session_9_10042022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_007_Session_10_05102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_007_Session_7_01072021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_007_Session_8_04102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_007_Session_9_23052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_010_Session_10_06102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_010_Session_7_15052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_010_Session_8_12102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_010_Session_9_25052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_017_Session_10_06102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_017_Session_7_13052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_017_Session_8_12102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_017_Session_9_25052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_018_Session_10_23062022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_018_Session_7_11052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_018_Session_8_11102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_018_Session_9_11102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_022_Session_10_11102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_022_Session_7_07052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_022_Session_8_11102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_022_Session_9_01062022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_024_Session_10_05102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_024_Session_7_12052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_024_Session_8_07102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_024_Session_9_24052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_026_Session_10_06102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_026_Session_7_15052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_026_Session_8_12102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_026_Session_9_25052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_027_Session_10_07102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_027_Session_7_13052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_027_Session_8_07102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_027_Session_9_26052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_031_Session_10_10102022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_031_Session_7_14052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_031_Session_8_11102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_031_Session_9_31052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_048_Session_10_31052022.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_048_Session_7_11052021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_048_Session_8_12102021.txt '
        '&& '
        'python main.py < '
        'C:/LWF/BayDetect/metadata/Karwendel_Rohdaten/KW_BatchCmds/pf1_createBIJSON/pf1_createBIJSON_KW_048_Session_9_3105_2022.txt '

    )
    return print('Finished !!')


def md_batchrun():
    os.system(
        'cd cameratraps/detection '
        '&& '
        # Insert new python commands below this line
                                                                        
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_003_Session_7_13052021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_003_Session_7_13052021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_003_Session_8_11102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_003_Session_8_11102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_003_Session_9_26052022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_003_Session_9_26052022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_005_Session_10_21092022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_005_Session_10_21092022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_005_Session_7_28062021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_005_Session_7_28062021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_005_Session_8_06102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_005_Session_8_06102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_005_Session_9_10042022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_005_Session_9_10042022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_007_Session_10_05102022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_007_Session_10_05102022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_007_Session_7_01072021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_007_Session_7_01072021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_007_Session_8_04102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_007_Session_8_04102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_007_Session_9_23052022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_007_Session_9_23052022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_010_Session_10_06102022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_010_Session_10_06102022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_010_Session_7_15052021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_010_Session_7_15052021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_010_Session_8_12102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_010_Session_8_12102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_010_Session_9_25052022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_010_Session_9_25052022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_017_Session_10_06102022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_017_Session_10_06102022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_017_Session_7_13052021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_017_Session_7_13052021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_017_Session_8_12102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_017_Session_8_12102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_017_Session_9_25052022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_017_Session_9_25052022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_018_Session_10_23062022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_018_Session_10_23062022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_018_Session_7_11052021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_018_Session_7_11052021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_018_Session_8_11102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_018_Session_8_11102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_018_Session_9_11102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_018_Session_9_11102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_022_Session_10_11102022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_022_Session_10_11102022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_022_Session_7_07052021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_022_Session_7_07052021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_022_Session_8_11102021_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_022_Session_8_11102021_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_022_Session_9_01062022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_022_Session_9_01062022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_024_Session_10_05102022_BI.json ' 
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_024_Session_10_05102022_MD.json ' 
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_024_Session_7_12052021_BI.json '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_024_Session_7_12052021_MD.json '
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_024_Session_8_07102021_BI.json '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_024_Session_8_07102021_MD.json '
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_024_Session_9_24052022_BI.json '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_024_Session_9_24052022_MD.json '
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_026_Session_10_06102022_BI.json '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_026_Session_10_06102022_MD.json '
        '&& '
        'python run_detector_batch.py md_v5a.0.0.pt '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_026_Session_7_15052021_BI.json '
        '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_026_Session_7_15052021_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_026_Session_8_12102021_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_026_Session_8_12102021_MD.json '
        # # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_026_Session_9_25052022_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_026_Session_9_25052022_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_027_Session_10_07102022_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_027_Session_10_07102022_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_027_Session_7_13052021_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_027_Session_7_13052021_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_027_Session_8_07102021_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_027_Session_8_07102021_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_027_Session_9_26052022_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_027_Session_9_26052022_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_031_Session_10_10102022_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_031_Session_10_10102022_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_031_Session_7_14052021_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_031_Session_7_14052021_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_031_Session_8_11102021_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_031_Session_8_11102021_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_031_Session_9_31052022_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_031_Session_9_31052022_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_048_Session_10_31052022_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_048_Session_10_31052022_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_048_Session_7_11052021_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_048_Session_7_11052021_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_048_Session_8_12102021_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_048_Session_8_12102021_MD.json '
        # '&& '
        # 'python run_detector_batch.py md_v5a.0.0.pt '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_BatchInput_StartSess7/KW_048_Session_9_3105_2022_BI.json '
        # '../../metadata/Karwendel_Rohdaten/KW_JSON/KW_MegaDetected/KW_048_Session_9_3105_2022_MD.json '

    )
    return print('Finished !!')


if __name__ == '__main__':

    intro_choice = input("Enter '1' to execute pf_batchrun() function \n"
                         "Enter '2' to execute md_batchrun() function \n"
                         "\n"
                         "Enter your choice here: ")

    intro_choice = int(intro_choice)

    if intro_choice == 1:
        print("\n'1' Selected! Batch-running processing function ..."
              "\n")
        pf_batchrun()

    elif intro_choice == 2:
        print("\n'2' Selected! Batch-running MegaDetector classification ..."
              "\n")
        md_batchrun()

    else:
        print("\nWrong choice, please re-run the script and follow the instructions !!!"
              "\n")
